### PR TITLE
Requested changes for arduino/reference-en#750

### PR DESCRIPTION
**Pull request by per1234**
Hi @AshutoshPandey123456. I have some changes to propose to your pull request arduino/reference-en#750. Unfortunately, GitHub's review system isn't powerful enough to support this particular case, so I'm just submitting them as a PR to the branch of your fork. If you merge this, it will automatically update the PR.

Please see the commit messages of the individual commits for explanation of the requested changes.

I'm happy to discuss my proposed modifications, but it is definitely going to be necessary to modify your PR before it can be merged because it would break the documentation generation system in its current state.

### CODE REVIEW

**Comment by AshutoshPandey123456** [comment]
@per1234

I agree with your reasoning on the modifications. I'll be more wary of these shortcomings in the future, thanks for the suggestions.

**Comment by AshutoshPandey123456** [comment]
@per1234

I agree with your reasoning on the modifications. I'll be more wary of these shortcomings in the future, thanks for the suggestions.

**Comment by ashpande** [comment]
@per1234

I agree with your reasoning on the modifications. I'll be more wary of these shortcomings in the future, thanks for the suggestions.

**Comment by AshutoshPandey123456** [comment]
@per1234

I agree with your reasoning on the modifications. I'll be more wary of these shortcomings in the future, thanks for the suggestions.

**Comment by AshutoshPandey123456** [comment]
@per1234

I agree with your reasoning on the modifications. I'll be more wary of these shortcomings in the future, thanks for the suggestions.

**Pull request merged**
